services:
  neo4j:
    image: neo4j:4.0.2-enterprise
    network_mode: "bridge"
    ports:
      - "10001:7687"
      - "10002:7473"
      - "10003:7474"
    restart: unless-stopped
    volumes:
      - /datadrive/neo4j/plugins:/plugins
      - /datadrive/neo4j/data:/data
      - /datadrive/neo4j/import:/import
      - /datadrive/neo4j/logs:/logs
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/neo123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_backup_enabled=true
      - NEO4J_dbms_transaction_timeout=60s
    logging:
      options:
        tag: "ImageName:{{.ImageName}}/Name:{{.Name}}/ID:{{.ID}}/ImageFullID:{{.ImageFullID}}"
